# docker compose file
# Author: 정근화

version: "3.7"

services:
  # mongo DB 컨테이너의 이름 : db
  mongo:
    image: mongo:4.2.1
    volumes:
      - ./docker/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jkh
      - MONGO_INITDB_ROOT_PASSWORD=rmsghk3346!
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet 1
      interval: 3s
      timeout: 1s
      retries: 10
      start_period: 40s

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=sampledb
      - DJANGO_DB_USERNAME=sampleuser
      - DJANGO_DB_PASSWORD=samplesecret
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    command: /start-dev.sh
    volumes:
      - ./:/app/
