# docker compose file
# Author: 정근화

version: "3.7"

services:
  # mongo DB 컨테이너의 이름 : db
  db:
    image: mongo:4.2.1
    # DB 이미지 호스트 볼륨 경로
    volumes:
      - ./docker/data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet 1
      interval: 3s
      timeout: 1s
      retries: 10
      start_period: 40s

  fcm:
    build:
      # 빌드할 디렉터리 경로
      context: ./fcm-pusher
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - db
    links:
      - db
    volumes:
      - /root/fcm_config:/root/fcm_config
